# Generated by Django 4.0.4 on 2022-09-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger_first_passenger_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last',
            field=models.CharField(max_length=64),
        ),
    ]
